version: '2'
services:
  github-api:
    container_name: github-api
    build:
      context: ./
      dockerfile: Dockerfile
    image: github-api:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
networks:
  spring-cloud-network:
    driver: bridge